sudoku/main/AbstractEnum.java:88 BASE
sudoku/main/AbstractEnum.java:89 BASE
sudoku/main/AbstractEnum.java:90 BASE
sudoku/main/AbstractEnum.java:91 BASE
sudoku/main/AbstractEnum.java:92 BASE
sudoku/main/AbstractEnum.java:93 BASE
sudoku/main/AbstractEnum.java:110 BASE
sudoku/main/AbstractEnum.java:111 BASE
sudoku/main/AbstractEnum.java:112 BASE
sudoku/main/AbstractEnum.java:113 BASE
sudoku/main/AbstractEnum.java:143 BASE
sudoku/main/AbstractEnum.java:144 BASE
sudoku/main/AbstractEnum.java:145 BASE
sudoku/main/AbstractEnum.java:146 BASE
sudoku/main/AbstractEnum.java:147 BASE
sudoku/main/AbstractEnum.java:161 BASE
sudoku/main/AbstractEnum.java:162 BASE
sudoku/main/AbstractEnum.java:163 BASE
sudoku/main/AbstractEnum.java:180 BASE
sudoku/main/AbstractEnum.java:196 BASE
sudoku/main/AbstractEnum.java:213 BASE
sudoku/main/AbstractEnum.java:227 BASE
sudoku/main/AbstractEnum.java:244 BASE
sudoku/main/AbstractEnum.java:245 BASE
sudoku/main/AbstractEnum.java:246 BASE
sudoku/main/AbstractEnum.java:252 BASE
sudoku/main/AbstractEnum.java:253 BASE
sudoku/main/AbstractEnum.java:254 BASE
sudoku/main/AbstractEnum.java:255 BASE
sudoku/main/AbstractEnum.java:256 BASE
sudoku/main/AbstractEnum.java:257 BASE
sudoku/main/AbstractEnum.java:263 BASE
sudoku/main/AbstractEnum.java:264 BASE
sudoku/main/AbstractEnum.java:265 BASE
sudoku/main/AbstractEnum.java:266 BASE
sudoku/main/AbstractEnum.java:267 BASE
sudoku/main/AbstractEnum.java:268 BASE
sudoku/main/AbstractEnum.java:274 BASE
sudoku/main/AbstractEnum.java:275 BASE
sudoku/main/AbstractEnum.java:276 BASE
sudoku/main/AbstractEnum.java:282 BASE
sudoku/main/AbstractEnum.java:283 BASE
sudoku/main/Board.java:32 BASE
sudoku/main/Board.java:33 BASE
sudoku/main/Board.java:34 BASE
sudoku/main/Board.java:35 BASE
sudoku/main/Board.java:49 BASE
sudoku/main/Board.java:55 BASE
sudoku/main/Board.java:57 BASE
sudoku/main/Board.java:58 BASE
sudoku/main/Board.java:59 BASE
sudoku/main/Board.java:60 BASE
sudoku/main/Board.java:61 BASE
sudoku/main/Board.java:62 BASE
sudoku/main/Board.java:63 BASE
sudoku/main/Board.java:64 BASE
sudoku/main/Board.java:70 BASE
sudoku/main/Board.java:77 GENERATOR
sudoku/main/Board.java:78 GENERATOR
sudoku/main/Board.java:79 GENERATOR
sudoku/main/Board.java:80 GENERATOR
sudoku/main/Board.java:81 GENERATOR
sudoku/main/Board.java:82 GENERATOR
sudoku/main/Board.java:83 GENERATOR
sudoku/main/Board.java:84 GENERATOR
sudoku/main/Board.java:85 GENERATOR
sudoku/main/Board.java:88 GENERATOR
sudoku/main/Board.java:89 GENERATOR
sudoku/main/Board.java:90 GENERATOR
sudoku/main/Board.java:91 GENERATOR
sudoku/main/Board.java:92 GENERATOR
sudoku/main/Board.java:93 GENERATOR
sudoku/main/Board.java:94 GENERATOR
sudoku/main/Board.java:95 GENERATOR
sudoku/main/Board.java:96 GENERATOR
sudoku/main/Board.java:97 GENERATOR
sudoku/main/Board.java:98 GENERATOR
sudoku/main/Board.java:99 GENERATOR
sudoku/main/Board.java:100 GENERATOR
sudoku/main/Board.java:77 BASE
sudoku/main/Board.java:78 BASE
sudoku/main/Board.java:79 BASE
sudoku/main/Board.java:80 BASE
sudoku/main/Board.java:81 BASE
sudoku/main/Board.java:82 BASE
sudoku/main/Board.java:83 BASE
sudoku/main/Board.java:84 BASE
sudoku/main/Board.java:85 BASE
sudoku/main/Board.java:88 BASE
sudoku/main/Board.java:89 BASE
sudoku/main/Board.java:90 BASE
sudoku/main/Board.java:91 BASE
sudoku/main/Board.java:92 BASE
sudoku/main/Board.java:93 BASE
sudoku/main/Board.java:94 BASE
sudoku/main/Board.java:95 BASE
sudoku/main/Board.java:96 BASE
sudoku/main/Board.java:97 BASE
sudoku/main/Board.java:98 BASE
sudoku/main/Board.java:99 BASE
sudoku/main/Board.java:100 BASE
sudoku/main/Board.java:101 BASE
sudoku/main/Board.java:109 SOLVER
sudoku/main/Board.java:110 SOLVER
sudoku/main/Board.java:111 SOLVER
sudoku/main/Board.java:112 SOLVER
sudoku/main/Board.java:109 BASE
sudoku/main/Board.java:110 BASE
sudoku/main/Board.java:111 BASE
sudoku/main/Board.java:112 BASE
sudoku/main/Board.java:113 BASE
sudoku/main/Board.java:120 SOLVER
sudoku/main/Board.java:121 SOLVER
sudoku/main/Board.java:122 SOLVER
sudoku/main/Board.java:123 SOLVER
sudoku/main/Board.java:124 SOLVER
sudoku/main/Board.java:125 SOLVER
sudoku/main/Board.java:120 BASE
sudoku/main/Board.java:121 BASE
sudoku/main/Board.java:122 BASE
sudoku/main/Board.java:123 BASE
sudoku/main/Board.java:124 BASE
sudoku/main/Board.java:125 BASE
sudoku/main/Board.java:126 BASE
sudoku/main/Board.java:133 SOLVER
sudoku/main/Board.java:134 SOLVER
sudoku/main/Board.java:135 SOLVER
sudoku/main/Board.java:136 SOLVER
sudoku/main/Board.java:137 SOLVER
sudoku/main/Board.java:138 SOLVER
sudoku/main/Board.java:139 SOLVER
sudoku/main/Board.java:140 SOLVER
sudoku/main/Board.java:141 SOLVER
sudoku/main/Board.java:142 SOLVER
sudoku/main/Board.java:143 SOLVER
sudoku/main/Board.java:133 BASE
sudoku/main/Board.java:134 BASE
sudoku/main/Board.java:135 BASE
sudoku/main/Board.java:136 BASE
sudoku/main/Board.java:137 BASE
sudoku/main/Board.java:138 BASE
sudoku/main/Board.java:139 BASE
sudoku/main/Board.java:140 BASE
sudoku/main/Board.java:141 BASE
sudoku/main/Board.java:142 BASE
sudoku/main/Board.java:143 BASE
sudoku/main/Board.java:144 BASE
sudoku/main/Board.java:151 SOLVER
sudoku/main/Board.java:152 SOLVER
sudoku/main/Board.java:153 SOLVER
sudoku/main/Board.java:154 SOLVER
sudoku/main/Board.java:155 SOLVER
sudoku/main/Board.java:156 SOLVER
sudoku/main/Board.java:157 SOLVER
sudoku/main/Board.java:158 SOLVER
sudoku/main/Board.java:159 SOLVER
sudoku/main/Board.java:151 BASE
sudoku/main/Board.java:152 BASE
sudoku/main/Board.java:153 BASE
sudoku/main/Board.java:154 BASE
sudoku/main/Board.java:155 BASE
sudoku/main/Board.java:156 BASE
sudoku/main/Board.java:157 BASE
sudoku/main/Board.java:158 BASE
sudoku/main/Board.java:159 BASE
sudoku/main/Board.java:160 BASE
sudoku/main/Board.java:167 SOLVER
sudoku/main/Board.java:168 SOLVER
sudoku/main/Board.java:169 SOLVER
sudoku/main/Board.java:170 SOLVER
sudoku/main/Board.java:171 SOLVER
sudoku/main/Board.java:172 SOLVER
sudoku/main/Board.java:173 SOLVER
sudoku/main/Board.java:174 SOLVER
sudoku/main/Board.java:175 SOLVER
sudoku/main/Board.java:176 SOLVER
sudoku/main/Board.java:177 SOLVER
sudoku/main/Board.java:178 SOLVER
sudoku/main/Board.java:179 SOLVER
sudoku/main/Board.java:180 SOLVER
sudoku/main/Board.java:181 SOLVER
sudoku/main/Board.java:167 BASE
sudoku/main/Board.java:168 BASE
sudoku/main/Board.java:169 BASE
sudoku/main/Board.java:170 BASE
sudoku/main/Board.java:171 BASE
sudoku/main/Board.java:172 BASE
sudoku/main/Board.java:173 BASE
sudoku/main/Board.java:174 BASE
sudoku/main/Board.java:175 BASE
sudoku/main/Board.java:176 BASE
sudoku/main/Board.java:177 BASE
sudoku/main/Board.java:178 BASE
sudoku/main/Board.java:179 BASE
sudoku/main/Board.java:180 BASE
sudoku/main/Board.java:181 BASE
sudoku/main/Board.java:182 BASE
sudoku/main/Board.java:189 STATES
sudoku/main/Board.java:190 STATES
sudoku/main/Board.java:191 STATES
sudoku/main/Board.java:192 STATES
sudoku/main/Board.java:193 STATES
sudoku/main/Board.java:189 BASE
sudoku/main/Board.java:190 BASE
sudoku/main/Board.java:191 BASE
sudoku/main/Board.java:192 BASE
sudoku/main/Board.java:193 BASE
sudoku/main/Board.java:194 BASE
sudoku/main/Board.java:201 STATES
sudoku/main/Board.java:202 STATES
sudoku/main/Board.java:201 BASE
sudoku/main/Board.java:202 BASE
sudoku/main/Board.java:203 BASE
sudoku/main/Board.java:210 STATES
sudoku/main/Board.java:211 STATES
sudoku/main/Board.java:210 BASE
sudoku/main/Board.java:211 BASE
sudoku/main/Board.java:212 BASE
sudoku/main/BoardManager.java:28 BASE
sudoku/main/BoardManager.java:30 STATES
sudoku/main/BoardManager.java:30 BASE
sudoku/main/BoardManager.java:31 BASE
sudoku/main/BoardManager.java:44 BASE
sudoku/main/BoardManager.java:46 BASE
sudoku/main/BoardManager.java:52 BASE
sudoku/main/BoardManager.java:53 BASE
sudoku/main/BoardManager.java:54 BASE
sudoku/main/BoardManager.java:55 BASE
sudoku/main/BoardManager.java:56 BASE
sudoku/main/BoardManager.java:57 BASE
sudoku/main/BoardManager.java:58 BASE
sudoku/main/BoardManager.java:59 BASE
sudoku/main/BoardManager.java:60 BASE
sudoku/main/BoardManager.java:61 BASE
sudoku/main/BoardManager.java:62 BASE
sudoku/main/BoardManager.java:63 BASE
sudoku/main/BoardManager.java:64 BASE
sudoku/main/BoardManager.java:65 BASE
sudoku/main/BoardManager.java:66 BASE
sudoku/main/BoardManager.java:67 BASE
sudoku/main/BoardManager.java:68 BASE
sudoku/main/BoardManager.java:69 BASE
sudoku/main/BoardManager.java:70 BASE
sudoku/main/BoardManager.java:71 BASE
sudoku/main/BoardManager.java:72 BASE
sudoku/main/BoardManager.java:73 BASE
sudoku/main/BoardManager.java:74 BASE
sudoku/main/BoardManager.java:75 BASE
sudoku/main/BoardManager.java:76 BASE
sudoku/main/BoardManager.java:77 BASE
sudoku/main/BoardManager.java:78 BASE
sudoku/main/BoardManager.java:79 BASE
sudoku/main/BoardManager.java:80 BASE
sudoku/main/BoardManager.java:81 BASE
sudoku/main/BoardManager.java:82 BASE
sudoku/main/BoardManager.java:83 BASE
sudoku/main/BoardManager.java:84 BASE
sudoku/main/BoardManager.java:85 BASE
sudoku/main/BoardManager.java:86 BASE
sudoku/main/BoardManager.java:87 BASE
sudoku/main/BoardManager.java:88 BASE
sudoku/main/BoardManager.java:89 BASE
sudoku/main/BoardManager.java:90 BASE
sudoku/main/BoardManager.java:91 BASE
sudoku/main/BoardManager.java:92 BASE
sudoku/main/BoardManager.java:98 BASE
sudoku/main/BoardManager.java:105 STATES
sudoku/main/BoardManager.java:106 STATES
sudoku/main/BoardManager.java:107 STATES
sudoku/main/BoardManager.java:108 STATES
sudoku/main/BoardManager.java:109 STATES
sudoku/main/BoardManager.java:105 BASE
sudoku/main/BoardManager.java:106 BASE
sudoku/main/BoardManager.java:107 BASE
sudoku/main/BoardManager.java:108 BASE
sudoku/main/BoardManager.java:109 BASE
sudoku/main/BoardManager.java:110 BASE
sudoku/main/BoardManager.java:119 STATES
sudoku/main/BoardManager.java:119 BASE
sudoku/main/BoardManager.java:120 BASE
sudoku/main/BoardManager.java:127 BASE
sudoku/main/BoardManager.java:128 BASE
sudoku/main/BoardManager.java:129 BASE
sudoku/main/BoardManager.java:135 BASE
sudoku/main/BoardManager.java:141 BASE
sudoku/main/BoardManager.java:142 BASE
sudoku/main/BoardManager.java:143 BASE
sudoku/main/BoardManager.java:144 BASE
sudoku/main/BoardManager.java:151 BASE
sudoku/main/BoardManager.java:157 EXTENDEDSUDOKU
sudoku/main/BoardManager.java:158 EXTENDEDSUDOKU
sudoku/main/BoardManager.java:159 EXTENDEDSUDOKU
sudoku/main/BoardManager.java:165 GENERATOR
sudoku/main/BoardManager.java:166 GENERATOR
sudoku/main/BoardManager.java:167 GENERATOR
sudoku/main/BoardManager.java:173 SOLVER
sudoku/main/BoardManager.java:175 SOLVER
sudoku/main/BoardManager.java:183 SOLVER
sudoku/main/BoardManager.java:189 SOLVER
sudoku/main/BoardManager.java:190 SOLVER
sudoku/main/BoardManager.java:191 SOLVER
sudoku/main/BoardManager.java:192 SOLVER
sudoku/main/BoardManager.java:193 SOLVER
sudoku/main/BoardManager.java:194 SOLVER
sudoku/main/BoardManager.java:195 SOLVER
sudoku/main/BoardManager.java:196 SOLVER
sudoku/main/BoardManager.java:197 SOLVER
sudoku/main/BoardManager.java:204 SOLVER
sudoku/main/BoardManager.java:205 SOLVER
sudoku/main/BoardManager.java:206 SOLVER
sudoku/main/BoardManager.java:207 SOLVER
sudoku/main/BoardManager.java:208 SOLVER
sudoku/main/BoardManager.java:209 SOLVER
sudoku/main/BoardManager.java:210 SOLVER
sudoku/main/BoardManager.java:211 SOLVER
sudoku/main/BoardManager.java:212 SOLVER
sudoku/main/BoardManager.java:213 SOLVER
sudoku/main/BoardManager.java:214 SOLVER
sudoku/main/BoardManager.java:215 SOLVER
sudoku/main/BoardManager.java:218 SOLVER
sudoku/main/BoardManager.java:228 SOLVER
sudoku/main/BoardManager.java:229 SOLVER
sudoku/main/BoardManager.java:230 SOLVER
sudoku/main/BoardManager.java:231 SOLVER
sudoku/main/BoardManager.java:232 SOLVER
sudoku/main/BoardManager.java:233 SOLVER
sudoku/main/BoardManager.java:234 SOLVER
sudoku/main/BoardManager.java:235 SOLVER
sudoku/main/BoardManager.java:236 SOLVER
sudoku/main/BoardManager.java:237 SOLVER
sudoku/main/BoardManager.java:238 SOLVER
sudoku/main/BoardManager.java:239 SOLVER
sudoku/main/BoardManager.java:240 SOLVER
sudoku/main/BoardManager.java:241 SOLVER
sudoku/main/BoardManager.java:242 SOLVER
sudoku/main/BoardManager.java:243 SOLVER
sudoku/main/BoardManager.java:244 SOLVER
sudoku/main/BoardManager.java:245 SOLVER
sudoku/main/BoardManager.java:246 SOLVER
sudoku/main/BoardManager.java:247 SOLVER
sudoku/main/BoardManager.java:248 SOLVER
sudoku/main/BoardManager.java:249 SOLVER
sudoku/main/BoardManager.java:250 SOLVER
sudoku/main/BoardManager.java:251 SOLVER
sudoku/main/BoardManager.java:252 SOLVER
sudoku/main/BoardManager.java:253 SOLVER
sudoku/main/BoardManager.java:254 SOLVER
sudoku/main/BoardManager.java:255 SOLVER
sudoku/main/BoardManager.java:256 SOLVER
sudoku/main/BoardManager.java:257 SOLVER
sudoku/main/BoardManager.java:258 SOLVER
sudoku/main/BoardManager.java:259 SOLVER
sudoku/main/BoardManager.java:260 SOLVER
sudoku/main/BoardManager.java:261 SOLVER
sudoku/main/BoardManager.java:262 SOLVER
sudoku/main/BoardManager.java:263 SOLVER
sudoku/main/BoardManager.java:264 SOLVER
sudoku/main/BoardManager.java:265 SOLVER
sudoku/main/BoardManager.java:266 SOLVER
sudoku/main/BoardManager.java:267 SOLVER
sudoku/main/BoardManager.java:278 SOLVER
sudoku/main/BoardManager.java:279 SOLVER
sudoku/main/BoardManager.java:280 SOLVER
sudoku/main/BoardManager.java:281 SOLVER
sudoku/main/BoardManager.java:282 SOLVER
sudoku/main/BoardManager.java:283 SOLVER
sudoku/main/BoardManager.java:284 SOLVER
sudoku/main/BoardManager.java:285 SOLVER
sudoku/main/BoardManager.java:286 SOLVER
sudoku/main/BoardManager.java:287 SOLVER
sudoku/main/BoardManager.java:288 SOLVER
sudoku/main/BoardManager.java:289 SOLVER
sudoku/main/BoardManager.java:290 SOLVER
sudoku/main/BoardManager.java:291 SOLVER
sudoku/main/BoardManager.java:292 SOLVER
sudoku/main/BoardManager.java:293 SOLVER
sudoku/main/BoardManager.java:294 SOLVER
sudoku/main/BoardManager.java:295 SOLVER
sudoku/main/BoardManager.java:296 SOLVER
sudoku/main/BoardManager.java:297 SOLVER
sudoku/main/BoardManager.java:298 SOLVER
sudoku/main/BoardManager.java:299 SOLVER
sudoku/main/BoardManager.java:305 SOLVER
sudoku/main/BoardManager.java:306 SOLVER
sudoku/main/BoardManager.java:307 SOLVER
sudoku/main/BoardManager.java:308 SOLVER
sudoku/main/BoardManager.java:309 SOLVER
sudoku/main/BoardManager.java:310 SOLVER
sudoku/main/BoardManager.java:311 SOLVER
sudoku/main/BoardManager.java:312 SOLVER
sudoku/main/BoardManager.java:313 SOLVER
sudoku/main/BoardManager.java:314 SOLVER
sudoku/main/BoardManager.java:315 SOLVER
sudoku/main/BoardManager.java:316 SOLVER
sudoku/main/BoardManager.java:317 SOLVER
sudoku/main/BoardManager.java:318 SOLVER
sudoku/main/BoardManager.java:319 SOLVER
sudoku/main/BoardManager.java:320 SOLVER
sudoku/main/BoardManager.java:326 STATES
sudoku/main/BoardManager.java:329 STATES
sudoku/main/BoardManager.java:335 STATES
sudoku/main/BoardManager.java:336 STATES
sudoku/main/BoardManager.java:337 STATES
sudoku/main/BoardManager.java:338 STATES
sudoku/main/BoardManager.java:344 UNDO
sudoku/main/BoardManager.java:345 UNDO
sudoku/main/BoardManager.java:346 UNDO
sudoku/main/BoardManager.java:347 UNDO
sudoku/main/Field.java:40 BASE
sudoku/main/Field.java:41 BASE
sudoku/main/Field.java:42 BASE
sudoku/main/Field.java:44 COLOR
sudoku/main/Field.java:44 BASE
sudoku/main/Field.java:45 BASE
sudoku/main/Field.java:46 BASE
sudoku/main/Field.java:48 SOLVER
sudoku/main/Field.java:49 SOLVER
sudoku/main/Field.java:50 SOLVER
sudoku/main/Field.java:51 SOLVER
sudoku/main/Field.java:48 BASE
sudoku/main/Field.java:49 BASE
sudoku/main/Field.java:50 BASE
sudoku/main/Field.java:51 BASE
sudoku/main/Field.java:52 BASE
sudoku/main/Field.java:62 BASE
sudoku/main/Field.java:63 BASE
sudoku/main/Field.java:64 BASE
sudoku/main/Field.java:65 BASE
sudoku/main/Field.java:67 COLOR
sudoku/main/Field.java:67 BASE
sudoku/main/Field.java:68 BASE
sudoku/main/Field.java:69 BASE
sudoku/main/Field.java:71 SOLVER
sudoku/main/Field.java:71 BASE
sudoku/main/Field.java:72 BASE
sudoku/main/Field.java:78 BASE
sudoku/main/Field.java:79 BASE
sudoku/main/Field.java:80 BASE
sudoku/main/Field.java:81 BASE
sudoku/main/Field.java:83 COLOR
sudoku/main/Field.java:83 BASE
sudoku/main/Field.java:84 BASE
sudoku/main/Field.java:85 BASE
sudoku/main/Field.java:87 SOLVER
sudoku/main/Field.java:87 BASE
sudoku/main/Field.java:88 BASE
sudoku/main/Field.java:98 BASE
sudoku/main/Field.java:108 BASE
sudoku/main/Field.java:118 BASE
sudoku/main/Field.java:125 GENERATOR
sudoku/main/Field.java:125 BASE
sudoku/main/Field.java:126 BASE
sudoku/main/Field.java:134 SOLVER
sudoku/main/Field.java:134 BASE
sudoku/main/Field.java:135 BASE
sudoku/main/Field.java:146 SOLVER
sudoku/main/Field.java:146 BASE
sudoku/main/Field.java:147 BASE
sudoku/main/Field.java:155 SOLVER
sudoku/main/Field.java:156 SOLVER
sudoku/main/Field.java:157 SOLVER
sudoku/main/Field.java:158 SOLVER
sudoku/main/Field.java:159 SOLVER
sudoku/main/Field.java:160 SOLVER
sudoku/main/Field.java:161 SOLVER
sudoku/main/Field.java:162 SOLVER
sudoku/main/Field.java:163 SOLVER
sudoku/main/Field.java:164 SOLVER
sudoku/main/Field.java:165 SOLVER
sudoku/main/Field.java:155 BASE
sudoku/main/Field.java:156 BASE
sudoku/main/Field.java:157 BASE
sudoku/main/Field.java:158 BASE
sudoku/main/Field.java:159 BASE
sudoku/main/Field.java:160 BASE
sudoku/main/Field.java:161 BASE
sudoku/main/Field.java:162 BASE
sudoku/main/Field.java:163 BASE
sudoku/main/Field.java:164 BASE
sudoku/main/Field.java:165 BASE
sudoku/main/Field.java:166 BASE
sudoku/main/Field.java:173 SOLVER
sudoku/main/Field.java:174 SOLVER
sudoku/main/Field.java:175 SOLVER
sudoku/main/Field.java:176 SOLVER
sudoku/main/Field.java:177 SOLVER
sudoku/main/Field.java:178 SOLVER
sudoku/main/Field.java:179 SOLVER
sudoku/main/Field.java:173 BASE
sudoku/main/Field.java:174 BASE
sudoku/main/Field.java:175 BASE
sudoku/main/Field.java:176 BASE
sudoku/main/Field.java:177 BASE
sudoku/main/Field.java:178 BASE
sudoku/main/Field.java:179 BASE
sudoku/main/Field.java:180 BASE
sudoku/main/Field.java:187 STATES
sudoku/main/Field.java:188 STATES
sudoku/main/Field.java:189 STATES
sudoku/main/Field.java:190 STATES
sudoku/main/Field.java:191 STATES
sudoku/main/Field.java:187 BASE
sudoku/main/Field.java:188 BASE
sudoku/main/Field.java:189 BASE
sudoku/main/Field.java:190 BASE
sudoku/main/Field.java:191 BASE
sudoku/main/Field.java:192 BASE
sudoku/main/Field.java:199 STATES
sudoku/main/Field.java:200 STATES
sudoku/main/Field.java:201 STATES
sudoku/main/Field.java:202 STATES
sudoku/main/Field.java:199 BASE
sudoku/main/Field.java:200 BASE
sudoku/main/Field.java:201 BASE
sudoku/main/Field.java:202 BASE
sudoku/main/Field.java:203 BASE
sudoku/main/Field.java:210 STATES
sudoku/main/Field.java:211 STATES
sudoku/main/Field.java:212 STATES
sudoku/main/Field.java:213 STATES
sudoku/main/Field.java:210 BASE
sudoku/main/Field.java:211 BASE
sudoku/main/Field.java:212 BASE
sudoku/main/Field.java:213 BASE
sudoku/main/Field.java:214 BASE
sudoku/main/ForcedField.java:10 SOLVER
sudoku/main/ForcedField.java:11 SOLVER
sudoku/main/ForcedField.java:12 SOLVER
sudoku/main/ForcedField.java:13 SOLVER
sudoku/main/ForcedField.java:14 SOLVER
sudoku/main/ForcedField.java:15 SOLVER
sudoku/main/ForcedField.java:16 SOLVER
sudoku/main/ForcedNumber.java:12 SOLVER
sudoku/main/ForcedNumber.java:14 SOLVER
sudoku/main/ForcedNumber.java:16 SOLVER
sudoku/main/ForcedNumber.java:17 SOLVER
sudoku/main/ForcedNumber.java:18 SOLVER
sudoku/main/ForcedNumber.java:20 SOLVER
sudoku/main/ForcedNumber.java:21 SOLVER
sudoku/main/ForcedNumber.java:22 SOLVER
sudoku/main/ForcedNumber.java:23 SOLVER
sudoku/main/ForcedNumber.java:24 SOLVER
sudoku/main/ForcedNumber.java:25 SOLVER
sudoku/main/ForcedNumber.java:26 SOLVER
sudoku/main/ForcedNumber.java:27 SOLVER
sudoku/main/ForcedNumber.java:28 SOLVER
sudoku/main/ForcedNumber.java:29 SOLVER
sudoku/main/ForcedNumber.java:30 SOLVER
sudoku/main/ForcedNumber.java:31 SOLVER
sudoku/main/ForcedNumber.java:32 SOLVER
sudoku/main/ForcedNumber.java:33 SOLVER
sudoku/main/ForcedNumber.java:34 SOLVER
sudoku/main/ForcedNumber.java:35 SOLVER
sudoku/main/ForcedNumber.java:36 SOLVER
sudoku/main/Guesser.java:14 SOLVER
sudoku/main/Guesser.java:15 SOLVER
sudoku/main/Guesser.java:16 SOLVER
sudoku/main/Guesser.java:17 SOLVER
sudoku/main/Guesser.java:18 SOLVER
sudoku/main/Guesser.java:19 SOLVER
sudoku/main/Guesser.java:20 SOLVER
sudoku/main/Guesser.java:21 SOLVER
sudoku/main/Guesser.java:22 SOLVER
sudoku/main/Guesser.java:23 SOLVER
sudoku/main/Guesser.java:24 SOLVER
sudoku/main/Guesser.java:25 SOLVER
sudoku/main/Guesser.java:26 SOLVER
sudoku/main/Guesser.java:28 SOLVER
sudoku/main/Guesser.java:29 SOLVER
sudoku/main/Guesser.java:30 SOLVER
sudoku/main/Guesser.java:31 SOLVER
sudoku/main/Guesser.java:32 SOLVER
sudoku/main/Guesser.java:33 SOLVER
sudoku/main/Guesser.java:34 SOLVER
sudoku/main/Guesser.java:35 SOLVER
sudoku/main/Guesser.java:36 SOLVER
sudoku/main/Guesser.java:37 SOLVER
sudoku/main/Guesser.java:38 SOLVER
sudoku/main/Guesser.java:39 SOLVER
sudoku/main/Guesser.java:40 SOLVER
sudoku/main/Structure.java:17 BASE
sudoku/main/Structure.java:18 BASE
sudoku/main/Structure.java:24 BASE
sudoku/main/SudokuFacade.java:18 BASE
sudoku/main/SudokuFacade.java:20 GENERATOR
sudoku/main/SudokuFacade.java:20 BASE
sudoku/main/SudokuFacade.java:21 BASE
sudoku/main/SudokuFacade.java:37 BASE
sudoku/main/SudokuFacade.java:38 BASE
sudoku/main/SudokuFacade.java:39 BASE
sudoku/main/SudokuFacade.java:40 BASE
sudoku/main/SudokuFacade.java:41 BASE
sudoku/main/SudokuFacade.java:42 BASE
sudoku/main/SudokuFacade.java:43 BASE
sudoku/main/SudokuFacade.java:44 BASE
sudoku/main/SudokuFacade.java:46 SOLVER
sudoku/main/SudokuFacade.java:47 SOLVER
sudoku/main/SudokuFacade.java:48 SOLVER
sudoku/main/SudokuFacade.java:49 SOLVER
sudoku/main/SudokuFacade.java:50 SOLVER
sudoku/main/SudokuFacade.java:51 SOLVER
sudoku/main/SudokuFacade.java:52 SOLVER
sudoku/main/SudokuFacade.java:53 SOLVER
sudoku/main/SudokuFacade.java:46 BASE
sudoku/main/SudokuFacade.java:47 BASE
sudoku/main/SudokuFacade.java:48 BASE
sudoku/main/SudokuFacade.java:49 BASE
sudoku/main/SudokuFacade.java:50 BASE
sudoku/main/SudokuFacade.java:51 BASE
sudoku/main/SudokuFacade.java:52 BASE
sudoku/main/SudokuFacade.java:53 BASE
sudoku/main/SudokuFacade.java:54 BASE
sudoku/main/SudokuFacade.java:66 GENERATOR
sudoku/main/SudokuFacade.java:80 STATES
sudoku/main/SudokuFacade.java:81 STATES
sudoku/main/SudokuFacade.java:82 STATES
sudoku/main/SudokuFacade.java:83 STATES
sudoku/main/SudokuFacade.java:84 STATES
sudoku/main/SudokuFacade.java:85 STATES
sudoku/main/SudokuFacade.java:86 STATES
sudoku/main/SudokuFacade.java:87 STATES
sudoku/main/SudokuFacade.java:88 STATES
sudoku/main/SudokuFacade.java:97 STATES
sudoku/main/SudokuFacade.java:98 STATES
sudoku/main/SudokuFacade.java:99 STATES
sudoku/main/SudokuFacade.java:100 STATES
sudoku/main/SudokuFacade.java:101 STATES
sudoku/main/SudokuFacade.java:102 STATES
sudoku/main/SudokuFacade.java:103 STATES
sudoku/main/SudokuFacade.java:112 EXTENDEDSUDOKU
sudoku/main/SudokuFacade.java:121 SOLVER
sudoku/main/SudokuFacade.java:122 SOLVER
sudoku/main/SudokuFacade.java:123 SOLVER
sudoku/main/SudokuFacade.java:124 SOLVER
sudoku/main/SudokuFacade.java:125 SOLVER
sudoku/main/SudokuFacade.java:126 SOLVER
sudoku/main/SudokuFacade.java:127 SOLVER
sudoku/main/SudokuFacade.java:136 UNDO
sudoku/main/SudokuGenerator.java:12 GENERATOR
sudoku/main/SudokuGenerator.java:13 GENERATOR
sudoku/main/SudokuGenerator.java:14 GENERATOR
sudoku/main/SudokuGenerator.java:15 GENERATOR
sudoku/main/SudokuGenerator.java:21 GENERATOR
sudoku/main/SudokuGenerator.java:22 GENERATOR
sudoku/main/SudokuGenerator.java:23 GENERATOR
sudoku/main/SudokuGenerator.java:24 GENERATOR
sudoku/main/SudokuGenerator.java:27 GENERATOR
sudoku/main/SudokuGenerator.java:28 GENERATOR
sudoku/main/SudokuGenerator.java:29 GENERATOR
sudoku/main/SudokuGenerator.java:30 GENERATOR
sudoku/main/SudokuGenerator.java:31 GENERATOR
sudoku/main/SudokuGenerator.java:32 GENERATOR
sudoku/main/SudokuGenerator.java:33 GENERATOR
sudoku/main/SudokuGenerator.java:34 GENERATOR
sudoku/main/SudokuGenerator.java:35 GENERATOR
sudoku/main/SudokuGenerator.java:36 GENERATOR
sudoku/main/SudokuGenerator.java:37 GENERATOR
sudoku/main/SudokuGenerator.java:38 GENERATOR
sudoku/main/SudokuGenerator.java:39 GENERATOR
sudoku/main/SudokuGenerator.java:40 GENERATOR
sudoku/main/SudokuGenerator.java:41 GENERATOR
sudoku/main/SudokuGenerator.java:47 GENERATOR
sudoku/main/SudokuGenerator.java:48 GENERATOR
sudoku/main/SudokuGenerator.java:49 GENERATOR
sudoku/main/SudokuGenerator.java:50 GENERATOR
sudoku/main/SudokuGenerator.java:51 GENERATOR
sudoku/main/SudokuGenerator.java:53 GENERATOR
sudoku/main/SudokuGenerator.java:54 GENERATOR
sudoku/main/SudokuGenerator.java:55 GENERATOR
sudoku/main/SudokuGenerator.java:57 GENERATOR
sudoku/main/SudokuGenerator.java:58 GENERATOR
sudoku/main/SudokuGenerator.java:59 GENERATOR
sudoku/main/SudokuGenerator.java:60 GENERATOR
sudoku/main/SudokuGenerator.java:61 GENERATOR
sudoku/main/SudokuGenerator.java:62 GENERATOR
sudoku/main/SudokuGenerator.java:63 GENERATOR
sudoku/main/SudokuGenerator.java:64 GENERATOR
sudoku/main/SudokuGenerator.java:65 GENERATOR
sudoku/main/SudokuGenerator.java:66 GENERATOR
